### ISSUE TITLE
references SVN in bin/mkdistro.sh

### ISSUE THREAD

**Issue by kryton** [YahooArchive/oozie#1]
there is a 'git info' type thing here - http://justamemo.com/2009/02/09/git-info-almost-like-svn-info/ which may help

**Comment by tucu00** [comment]
we were using SVN internally, we'll fix that. thxs

**Comment by rvs** [comment]
Closed by 783df7436fca66600d2ca7e719a81fd33f271775 references SVN in bin/mkdistro.sh
