### ISSUE TITLE
some maven plugins are not found anymore

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#104]
It seems that one of the default maven repositories either is down of it does not host the maven-compiler-plugin anymore.

By adding the following entry as plugin repository in the pom.xml the plugin is picked up again

```
<pluginRepository>
      <id>apache-releases</id>
      <url>https://repository.apache.org/content/repositories/releases</url>
      <snapshots>
          <enabled>false</enabled>
      </snapshots>
</pluginRepository>
```

**Comment by rvs** [comment]
So which artifact exactly is failing? 

I'm slightly concerned with the amount of different repos we have configured (although your recent change cut that down significantly).

**Comment by tucu00** [comment]
maven-compiler-plugin 2.0.2 is not found anymore if you start with a fresh M2 cache

**Comment by rvs** [comment]
This is odd. Here's where my maven pulls it from:

http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.0.2/maven-compiler-plugin-2.0.2.jar

And here are the details of my Maven:

```
$ mvn --version
Apache Maven 2.2.0 (r788681; 2009-06-26 06:04:01-0700)
Java version: 1.6.0_17
Java home: /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x" version: "10.6.2" arch: "i386" Family: "mac"
```

**Comment by tucu00** [comment]
My maven is 2.2.1. Other than that i don't know what to say, it just does not work for me without the apache release repo for plugins

**Comment by rvs** [comment]
Closing for now as NOT REPRODUCIBLE.
