### ISSUE TITLE
Define Bundle Interface and provide implementation for Bundle Back end.

### ISSUE THREAD

**Issue by bansalmayank** [YahooArchive/oozie#122]
We need to define the interface for the Bundle and implementation for the JSON object for the client.
We also have to write the store and store service along with bundle bean to communicate with open jpa. We also need to change the persistence.xml for configuration changes.

**Comment by brookwc** [comment]
Closed by c917e8411c27a75f0018c184ba0272bbe47a5dc6 Added Bundle Functionality interface and store level

**Comment by mislam77-zz** [comment]
Done in another issue.
