### ISSUE TITLE
Query GET_WORKFLOWS_COLUMNS should order by createdTimestamp

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#125]
A workflow job might be killed before start_time was given. To fix this, we have to
change the query of jobs to be sorted by created_time instead of start_time.

The query will be like this:
    select w.id, w.appName, w.status, w.run, w.user, w.group, w.createdTimestamp, 
    w.startTimestamp, w.lastModifiedTimestamp, w.endTimestamp from 
    WorkflowJobBean w order by w.createdTimestamp desc

**Comment by brookwc** [comment]
Closed by 19e0f4bbafafa953f113c4cb9d3335ea608bcd8d Query GET_WORKFLOWS_COLUMNS should order by createdTimestamp instead of starttime
