### ISSUE TITLE
Oozie uses excessive memory when doing purging

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#141]
When there are many coordinator jobs/actions eligible for purge, Oozie becomes a memory hog when purging these jobs/actions. Oozie will purge coordinator actions first then coordinator jobs within one transaction. First we delete some actions and then we have select count queries on actions, this causes OpenJPA to create a large number of CoordinatorActionBean objects - eating up lots of memory.

To fix this, we need to have two transactions, one for deleting actions and one for deleting jobs. Then we will not run into this scenario where you have select count queries on some table with uncommitted changes.

**Comment by brookwc** [comment]
Along the way, found another problem for purging workflow jobs/actions. There is no limit imposed at all. Therefore if you have lots of qualified workflow jobs/actions to purge (say > 10,000) , memory usage just blows up. 

In light of this, change the issue subject to be more general.

**Comment by mislam77-zz** [comment]
Closed by 4f3ff42e2994d9cb64b42e4f58371f491e644164 Oozie uses excessive memory when doing purging
