### ISSUE TITLE
Log instances should be all static

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#142]
Many classes create Log instance as local/instance variables.

In a long running system this creates a large number of dangling Log objects until (if) they are GCed.

**Comment by mislam77-zz** [comment]
Is the issue #115 the same?

**Comment by tucu00** [comment]
no it is not, #115 is about the job context for the log message, this one is about Log variables

**Comment by tucu00** [comment]
Consolidated in the work of #318
