### ISSUE TITLE
Add Workflow JPA commands

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#144]
Add Workflow JPA commands

**Comment by angeloh** [comment]
Closed by 01b6a1edcd29563495fc8e5e6929fb0af506b8e3 Add Coordinator JPA commands. Closed by 01b6a1edcd29563495fc8e5e6929fb0af506b8e3 Add Workflow JPA commands.

**Comment by angeloh** [comment]
Closed by 01b6a1edcd29563495fc8e5e6929fb0af506b8e3 Add Coordinator JPA commands. Closed by 01b6a1edcd29563495fc8e5e6929fb0af506b8e3 Add Workflow JPA commands.

**Comment by mislam77-zz** [comment]
Done in another issue.
