### ISSUE TITLE
Modify the logic of adding .so and .so.1 files into cache

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#166]
It is related to code at JavaActionExecutor:addToCache() method

 String fileName = filePath.substring(filePath.lastIndexOf("/") + 1);
                if (fileName.endsWith(".so") || fileName.contains(".so.")) {  // .so files
                    if (!fileName.endsWith(".so")) {
                        int extAt = fileName.indexOf(".so.");
                        fileName = fileName.substring(0, extAt + 3);
                    }
                    uri = new Path(path.toString() + "#" + fileName).toUri();
                    uri = new URI(uri.getPath());
                }

The following things should work in <file> tag.
1. a.so.1 to be linked as a.so.1
2. a.so.1#b.so to be linked as b.so
3.  a.so#a.so should be linked as a.so
4. a.so should be linked as a.so.

**Comment by bwhite** [comment]
Same problem here.

When using libgfortran.so.3
libgfortran.so.3 is linked as libgfortran.so. For some programs this doesn't matter, for others it does. It matches based on blah.so.*, but it should keep the \* in the linked name.

Also folder/libgfortran.so.3#libgfortran.so.3 gives a URISyntaxException.

This is on the CDH3 version of oozie.

**Comment by bwhite** [comment]
I made a work around for Streaming users that changes to a directory "a" and then runs the program with whatever args you have.  You put all of your files into an archive and use <archive>myarc.tar.gz#a</archive>, now with this wrapper you are in the proper directory with all of the correct names.  Use it like ./wrapper.py my_streaming_mapper <my_mapper_args>

http://pastebin.com/hPnHjybX

Of course this is just a temporary fix.

**Comment by angeloh** [comment]
Closed by 534f7c2a6e2d1440f19c34a8cc8975c01e0d9014 Modify the logic of adding .so and .so.1 files into cache
