### ISSUE TITLE
WorkflowFunctionalSpec needs to fix chmod examples

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#182]
The following examples are wrong. 
1. 
      <chmod path='${jobOutput}' permissions='-rwxrw-rw-'>
                <dir-files>true</dir-files>
      </chmod>
Try this, it will return error:
org.apache.oozie.command.CommandException: E0701: XML schema error, cvc-complex-type.2.1: Element 'chmod' must have no
character or element information item [children], because the type's content type is empty.

2 The quote is wrong.
        <chmod path='[PATH]' permissions='[PERMISSIONS]' dir-files="false />

**Comment by tucu00** [comment]
Closed by b543030c358c90fb555ff6f5a670c0b8d90bb499 WorkflowFunctionalSpec needs to fix chmod examples
