### ISSUE TITLE
Oozie build should use publicly released Hadoop artifacts

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#183]
The Hadoop version used by Oozie build (specified in the main pom) is:

com.yahoo.hadoop:hadoop-core:0.20.104.1 (this is group:name:version)
- There is not tag in GH yahoo/hadoop that corresponds to that version
- The version returned Hadoop VersionInfo class is 'Unknown'

This complicates my integration with Hive as I need a Hadoop JAR with
a correct version.

Plus it would be good to know what source code of Hadoop the JAR corresponds to.

**Comment by rvs** [comment]
I have just published new artifacts corresponding to the following tag on GitHub:
     https://github.com/yahoo/hadoop-common/tree/yahoo-hadoop-0.20.104.2

Will this solve your problem? Can this issue be closed now?

Btw, we will HAVE to bump the version of hadoop we depend upon to 0.20.104.2 for the upcoming authentication code integration. We might as well do it now if you ask me.

Thanks,
Roman.

**Comment by tucu00** [comment]
great, i'll use this issue to do a pull request of the pom changed to the new version once the testcases finish

**Comment by tucu00** [comment]
Closed by adc69b8d4a5fbcad597034b02fd905fc85f7ecb2 update Oozie build to use Hadoop 0.20.104.2
