### ISSUE TITLE
bin/mkdistro.sh -DskipTests -dmysql -uroot -llocalhost:3306/oozie fails

### ISSUE THREAD

**Issue by kryton** [YahooArchive/oozie#2]
when I run it, I get
- mvn clean install -Dbuild.time=2010.07.16-13:47:01GMT -Dsvn.revision=GIT -Dsvn.url=git://github.com/yahoo/oozie.git -DskipTests -dmysql -uroot -llocalhost:3306/oozie
  Unable to parse command line options: Unrecognized option: -dmysql

**Comment by tucu00** [comment]
Please try running

$ bin/mkdistro.sh -dmysql -uroot -llocalhost:3306/oozie -DskipTests

It looks like the order of the parameters is important in current scripts

**Comment by tucu00** [comment]
with Oozie 2.2.0 this issue is not valid anymore as the build has changed and no SQL information is needed to configure the DB while doing a build.

**Comment by angeloh** [comment]
You also need to give MySQL jdbc url, user name and password to oozie-site.xml. Please refer to http://yahoo.github.com/oozie/releases/2.2.0/AG_Install.html#Database_Configuration.

**Comment by mislam77-zz** [comment]
As per previous comments, this is no longer valid in 2.2.x.
Closing the issue.
