### ISSUE TITLE
Update documentation to not refer to SSH, HTTP, and Email actions

### ISSUE THREAD

**Issue by hammer** [YahooArchive/oozie#28]
According to Alejandro, these have been deprecated.

**Comment by rvs** [comment]
Hmm. SSH seems to be there. Am I missing something?

**Comment by tucu00** [comment]
HTTP, EMAIL should be removed.

SSH is there, it should be deprecated.

**Comment by tucu00** [comment]
HTTP/EMAIL actions are not in the spec anymore (they've been removed already).

SSH is there but deprecated, it should stay there.
