### ISSUE TITLE
JPA log configuration uses wrong variable

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#296]
It is currently using:

  log4j.appender.openjpa.File=${oozie.home}/logs/oozie-jpa.log

It should use:

  log4j.appender.openjpa.File=${oozie.log.dir}/logs/oozie-jpa.log

**Comment by angeloh** [comment]
Would the path be XXXX/logs/logs/oozie-jpa.log?

**Comment by tucu00** [comment]
mmmhh, it should be ${oozie.log.dir}/oozie-jpa.log

**Comment by tucu00** [comment]
Closed by b89409fddc64ae97110bd3513668ec3c99110e2e JPA log configuration uses wrong variable
