### ISSUE TITLE
Throttle coordinator action/workflow creation per coordinator job 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#361]
Currently, if there are thousands of eligible  coordinator actions  to be created (e.g. catch-up mode) for one coordinator job, oozie creates all of them once and overloading the system.

This thing needs to be controlled and should only materialized X number of active actions per coordinator job. The
value of X should be configurable whether in oozie level or per job level that needs to be decided. 

In addition, there should be a way for customer to define the order by which job creation should be followed.  For
example, if there are 1000 actions ready to be created which X actions should be created first. Such as FIFO or LIFO.

This will definitely reduce the load on the internal queue.

**Comment by mislam77-zz** [comment]
Please comment on these open questions:
- How the throttling value/order should be defined? 
  - system wide/ System defined.
  - per job based/ User defined.

**Comment by tucu00** [comment]
IMO this should be system wide. system admins should control this, not users.

action materialization being FIFO/LIFO/lastOnly is already defined in the spec. 

I presume it is implemented, correct?

**Comment by mislam77-zz** [comment]
No. it was not implemented.
There is similar thing in WF submission when a lot coordinator actions ready to execute, oozie throttles using "concurrency" and order such as FIFO/LIFO.
I think you were confused with this.

The issue is for throttling during action creation.

Throttling configuration in system level might create some future issue. For example, at some point, a user has 100 actions to be materialized but system throttling value is :7. All 7 actions are waiting for data . However, he has the data for 10th and 12th instances. In this case, if he could give the throttling value of  12, his ready jobs would have been started.

**Comment by mislam77-zz** [comment]
Also finding a "good" value that will be applicable for "all types" of jobs is a challenge.
For example, for a monthly job a value of 3 is sufficient, however for minutes job it is not.

**Comment by anew** [comment]
I think that this should be user-defined, depending on the frequency of a job. And there should be a system-wide, admin-defined cap to protect Oozie's resources from "greedy" users.

**Comment by mislam77-zz** [comment]
How a user will define this value? Should we overload the meaning of "concurrency" used for "ready" job? OR there should be a new parameter like "max_active_action"?

**Comment by brookwc** [comment]
Closed by b0446e9ae627cb5edc8a34a50d545f0789607ebc Throttle coordinator action/workflow creation per coordinator job
