### ISSUE TITLE
getting the job configuration through oozie command line

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#362]
Reported by oozie user:
We need the job configuration of a workflow through command line. I see that there are options to get the rest (info, log and the job definition).

We are looking for the job conf to do a rerun of a particular stage of a workflow. If the rerun of a single stage can
done using the action configuration, please let us know.

**Comment by tucu00** [comment]
This infomation is already available via the HTTP REST API.

It comes in the JSON response with the Job Info.

This requires an additional option in the OozieCLI to display it.

**Comment by mislam77-zz** [comment]
yes that is the plan.
We will need to bump up the servlet version. As a result, need to support new version (v2).

**Comment by mislam77-zz** [comment]
After looking into details, it appears we don't need any new version of servlet for this. Wandering why  are we doing so many things for getting the job XML?

**Comment by brookwc** [comment]
Closed by 4ea44f7cf862078313b41b0cfcd65230cf35f210 getting the job configuration through oozie command line
