### ISSUE TITLE
Oozie maven repository(http://yahoo.github.com/maven/repository) not working (404)

### ISSUE THREAD

**Issue by florinpico** [YahooArchive/oozie#382]
Hello!
  The indicated maven repository(http://yahoo.github.com/maven/repository) for the oozie project is not available. Can you please check?
  Thank you!
 Florin

**Comment by tucu00** [comment]
I have a patch that uses Cloudera maven repo (https://github.com/tucu00/oozie/tree/GH-0226) we can use this as an interim solution until Apache has Hadoop/Pig JARs that Oozie can use.

**Comment by florinpico** [comment]
Ok seems that provided URL is fine
