### ISSUE TITLE
Create a set of JPA executors to replace part of old store service

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#383]
This issue is to create a set of JPA executors to replace part of old store service.
Note this is a small portion of the whole effort of the transition from store service to JPA executor acess pattern.

More specifically, this issue covers:
CoordActionGetForExternalIdJPAExecutor
CoordJobGetActionForNominalTimeJPAExecutor
CoordJobGetActionsForDatesJPAExecutor
CoordJobGetActionsJPAExecutor
CoordJobGetActionsSubsetJPAExecutor
CoordJobGetReadyActionsJPAExecutor
CoordJobGetRunningActionsCountJPAExecutor
WorkflowJobGetActionsJPAExecutor

**Comment by brookwc** [comment]
Note this issue depends on GH-0377.

**Comment by bansalmayank** [comment]
Closed by 481b2e7a2ff63621e8a8e7ff22ece50b73701deb Create a set of JPA executors to replace part of old store service
