### ISSUE TITLE
Adding New Workflow JPA Executor commands

### ISSUE THREAD

**Issue by bansalmayank** [YahooArchive/oozie#384]
Adding New Workflow JPA Executor commands

**Comment by angeloh** [comment]
Closed by b141c36ba4302b699de63fd9a12ce9d4ff3eed92 Adding new workflow jpa commands.

Closed by b141c36ba4302b699de63fd9a12ce9d4ff3eed92 Fixing Java doc

Closed by b141c36ba4302b699de63fd9a12ce9d4ff3eed92 Adding Test Cases

Closed by b141c36ba4302b699de63fd9a12ce9d4ff3eed92 Modifying Test Case

Closed by b141c36ba4302b699de63fd9a12ce9d4ff3eed92 Fixing Java Docs
