### ISSUE TITLE
Oozie console references the RowExpander.js file from an incorrect path.

### ISSUE THREAD

**Issue by aprabhakar** [YahooArchive/oozie#4]
The index.html file that launches oozie console references the RowExpander.js file from "ext-2.2/RowExpander.js". The correct location of this file however is "ext-2.2/examples/grid/RowExpander.js".

This causes the console to not show up correctly.

**Comment by aprabhakar** [comment]
There are two ways of fixing this - (1) modify the install script to move the RowExpander.js to the root of the ext-2.2 directory; or (2), update index.html to reference the path from the examples/grid directory.

This patch uses the second approach:

```
diff --git webapp/src/main/webapp/index.html webapp/src/main/webapp/index.html
index 42ddd42..1512754 100644
--- webapp/src/main/webapp/index.html
+++ webapp/src/main/webapp/index.html
@@ -7,7 +7,7 @@
     <!-- LIBS -->
     <script type="text/javascript" src="ext-2.2/adapter/ext/ext-base.js"></script>
     <script type="text/javascript" src="ext-2.2/ext-all.js"></script>
-    <script type="text/javascript" src="ext-2.2/RowExpander.js"></script>
+    <script type="text/javascript" src="ext-2.2/examples/grid/RowExpander.js"></script>
     <script type="text/javascript" src="json2.js"></script>
     <script type="text/javascript" src="oozie-console.js"></script>
 </head>
```

**Comment by tucu00** [comment]
Yes, I've missed that change in the Oozie 2 drop.

We'll fix that in the next drop
