### ISSUE TITLE
Another set of JPA Executors to be in

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#400]
They are:

core/src/main/java/org/apache/oozie/executor/jpa/CoordJobInfoGetCommand.java
core/src/main/java/org/apache/oozie/executor/jpa/CoordJobUpdateCommand.java
core/src/main/java/org/apache/oozie/executor/jpa/CoordJobsGetForPurgeCommand.java
core/src/main/java/org/apache/oozie/executor/jpa/CoordJobsToBeMaterializedCommand.java
core/src/main/java/org/apache/oozie/executor/jpa/SLAEventsGetForSeqIdCommand.java
core/src/main/java/org/apache/oozie/executor/jpa/WorkflowActionUpdateCommand.java

**Comment by mislam77-zz** [comment]
Closed by c7a7ae6bd3a4130124804d86b87ac3196ad5d7ee Another set of JPA Executors to be in
