### ISSUE TITLE
Create a logging utility class to set up log info.

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#401]
setLogInfo(...) methods have been removed from XCommand class. This issue is to provide a utility class for this.

**Comment by tucu00** [comment]
If we ripoff XLog in favor of SLF4J we get all the XLog logic for free

https://github.com/yahoo/oozie/issues/#issue/318

**Comment by mislam77-zz** [comment]
Closed by 7922f4aac51aea1df42d94213555a7b7c92bf117 Create a logging utility class to set up log info
