### ISSUE TITLE
update ojdbc version to 

### ISSUE THREAD

**Issue by rvs** [YahooArchive/oozie#41]
This is in response to an Oracle Bug 9577583:  False ORA-942 or other errors when multiple schemas have identical object names.
     http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-112010-090769.html

**Comment by tucu00** [comment]
The version in the core/pom.xml should be parameterized as it is done in for hadoop&pig and the current version should be in the root pom.xml.

This will allow people to easily force a build with a different version of the JDBC driver by specifiying in the build command line.

This should also be done for MySQL.

**Comment by rvs** [comment]
Closed by 99b04a5bbeecda16e6086429fbba0d723140bb58 update ojdbc version
