### ISSUE TITLE
Add jar files in <file> with smbolic link to java classpath

### ISSUE THREAD

**Issue by mchiang** [YahooArchive/oozie#42]
in workflow.xml, when use the following line:
<file>/tmp/a.jar#a.jar</file>

then this jar is added to distributed cache ("mapred.cache.files") only.

but this jar also needs to be in java classpath ("java.class.path").

**Comment by tucu00** [comment]
-1

If a file is symlinked, #a.jar, it means that the process expects the file in the running directory with the 'a.jar' name. If the process expects the JAR in the classpath, then the name should be irrelevant and no aliasing should be provided.

**Comment by brookwc** [comment]
agree - closing the issue.
