### ISSUE TITLE
(Job) Workflow return value

### ISSUE THREAD

**Issue by florinpico** [YahooArchive/oozie#425]
Hello!
   I have the following questions regarding the Oozie job workflow:
1. It is possible to return a value when a job is done?
2. An oozie workflow can be called from an outside world via web-service in a request/response manner? 
3. I would like to call from  Java client an Oozie workflow that is searching for some data and at the end it should return to the client the found data. Is this scenario plausible for Oozie?

  Thank you.
   Regards,
   Florin

**Comment by tucu00** [comment]
Florin,

For questions please use the oozie-users@yahoogroups.com alias.

If this still relevant please send your questions there.

Thanks.

Alejandro
