### ISSUE TITLE
Refactor a list of commands.

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#426]
They are:

WorkflowActionInfoXCommand.java
SubmitHttpXCommand.java
SubmitMRXCommand.java
SubmitPigXCommand.java
SubmitXCommand.java
CoordActionMaterializeXCommand.java
CoordJobMatLookupXCommand.java

**Comment by bansalmayank** [comment]
Closed by e35dc0306e42563cd8209839f9c1eddf6eb0b1c9 Refactor a list of commands
