### ISSUE TITLE
when extjs is not installed the index page should show a message indicating the reason why the console is not working

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#45]

**Comment by subtleGradient** [comment]
I'm on it!
Expect a pull rq soon

**Comment by tucu00** [comment]
Thanks Thomas

**Comment by subtleGradient** [comment]
https://github.com/yahoo/oozie/pull/220

**Comment by tucu00** [comment]
Closed by 095b3f38dcb39e35a8dc6e60195e9556bbf36712 display warning message in browser with extjs is not installed

Setting correct link to Quick Start docs.

Adding entry to release log.

Using branch with name convention.

(Thanks for the work Thomas)
