### ISSUE TITLE
added a bunch of bundle commands and services

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#457]
BundleJobInfo.java
BundleJobChangeXCommand.java
StatusTransitService.java
BundleEngineService.java
BundleEngineException.java
BundlePauseStartService.java
TestBundlePauseStartService.java
BundlePauseXCommand.java
TestBundlePauseUnpauseXCommand.java
PauseTransitionXCommand.java
BundleUnpauseXCommand.java
UnpauseTransitionXCommand.java

**Comment by mislam77-zz** [comment]
Closed by 756e8f2494fcd811fb6ed21466a3b4d63c6aa74e added a bunch of bundle commands and services
