### ISSUE TITLE
Mapping the workflow ID to coordinator ID 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#461]
Currently, Oozie doesn't seem to expose any programmatic way of identifying the coordinator ID (in particular which
action ID) that actually spawned a given workflow. Can you please check if this already exists & let us know? If
not, we would need this feature at the earliest as it's becoming really a pain to run a wild query on all coordinator
applications & grep this.

**Comment by brookwc** [comment]
Closed by 41b6ad1327699141fb6f67cd63adcbceba9b3a9c Mapping the workflow ID to coordinator ID
