### ISSUE TITLE
add another set of Bundle commands.

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#466]
BundleEngine.java
BundleActionId.java
BundleJobResumeXCommand.java
BundleJobSuspendXCommand.java
BundleKillXCommand.java
TestBundleKillXCommand.java

**Comment by angeloh** [comment]
Closed by dd92966e659540f8f2f90fc21c5c8ecf65af7bce Adding Bundle commands
BundleJobResumeXCommand.java
BundleJobSuspendXCommand.java
BundleKillXCommand.java
