### ISSUE TITLE
added some missing hookup code for bundle.

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#472]
include:

core/src/main/java/org/apache/oozie/servlet/BaseJobServlet.java
core/src/main/java/org/apache/oozie/servlet/ServletUtilities.java
core/src/main/java/org/apache/oozie/servlet/V1JobsServlet.java
core/src/main/java/org/apache/oozie/util/JobUtils.java

**Comment by angeloh** [comment]
Closed by 29ad813bbd5eb8b0b20b057d4dfc1fbaeded8296 added some missing hookup code for bundle
