### ISSUE TITLE
fail to rerun bundle with jobId null 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#481]
submit and start a bundle. coord job is created. both bundle and coord job RUNNING.
rerun the 1st coord action after it finishes.
oozie returns the "jobId null" exception.

the rerun command keeps failing, until the coord job status becomes "SUCCEEDED".

**Comment by brookwc** [comment]
Closed by b7e241e79af0fc779b1f166ec32646c23c04d6f5 fail to rerun bundle with jobId null
