### ISSUE TITLE
coord action 1's wf job is created much later than nominal time

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#491]
coord action 1 nominal time = 2010-12-09 05:37
it's workflow job created at = 2010-12-09 05:46
the subsequent actions had workflow jobs created at around nominal time.

$ oozie job -info 0001169-101204004045549-oozie-oozi-C
## Job ID : 0001169-101204004045549-oozie-oozi-C

Job Name : END2END-14
App Path : hdfs://gsbl90390.blue.ygrid.yahoo.com:8020/user/strat_ci/yoozie_test/coord/test_c14/coordinator.xml
## Status   : SUCCEEDED

ID                                       Status    Ext ID                               Err Code  Created  
Nominal Time
0001169-101204004045549-oozie-oozi-C@1   SUCCEEDED 0001170-101204004045549-oozie-oozi-W -         2010-12-09 05:36
## 2010-12-09 05:37

0001169-101204004045549-oozie-oozi-C@2   SUCCEEDED 0001171-101204004045549-oozie-oozi-W -         2010-12-09 05:36
## 2010-12-09 05:47

0001169-101204004045549-oozie-oozi-C@3   SUCCEEDED 0001172-101204004045549-oozie-oozi-W -         2010-12-09 05:36
## 2010-12-09 05:57

0001169-101204004045549-oozie-oozi-C@4   SUCCEEDED 0001173-101204004045549-oozie-oozi-W -         2010-12-09 05:36
## 2010-12-09 06:07

0001169-101204004045549-oozie-oozi-C@5   SUCCEEDED 0001174-101204004045549-oozie-oozi-W -         2010-12-09 05:36
## 2010-12-09 06:17

0001169-101204004045549-oozie-oozi-C@6   SUCCEEDED 0001175-101204004045549-oozie-oozi-W -         2010-12-09 05:36
## 2010-12-09 06:27

$ oozie job -info 0001170-101204004045549-oozie-oozi-W
## Job ID : 0001170-101204004045549-oozie-oozi-W

Workflow Name : mr-wf
App Path      :
hdfs://gsbl90390.blue.ygrid.yahoo.com:8020/user/strat_ci/yoozie_test/coord/test_c14/coord-mr/workflow.xml
Status        : SUCCEEDED
Run           : 0
User          : strat_ci
Group         : users
Created       : 2010-12-09 05:46
Started       : 2010-12-09 05:46
Last Modified : 2010-12-09 05:47
Ended         : 2010-12-09 05:47
## Actions

ID                                                                            Status    Ext ID                 Ext
## Status Err Code

0001170-101204004045549-oozie-oozi-W@hadoop1                                  OK

**Comment by angeloh** [comment]
Closed by 8e0a626b3c609bb924887eeb4e8c79320ac6dab9 coord action 1&#39;s wf job is created much later than nominal time
