### ISSUE TITLE
bundle status is RUNNING when fail to create coord job 

### ISSUE THREAD

**Issue by mchiang** [YahooArchive/oozie#497]
bundle failed to create coord job because one of the coord variable was missing. however the
bundle status was RUNNING (checked 10min after bundle submission, it was still RUNNING). 
when bundle failed to create coord job, its status should be "FAILED".

**Comment by angeloh** [comment]
Closed by e389089fecf24bc3be122f5f90caa6ee07eb4b9a bundle status is RUNNING when fail to create coord job
