### ISSUE TITLE
build-setup/setup-maven.sh uses bash-isms but references /bin/sh

### ISSUE THREAD

**Issue by rschultz** [YahooArchive/oozie#5]
Script defines a function and therefore fails on systems where /bin/sh is not bash.

Suggest:

--- setup-maven.sh.orig 2010-09-08 16:10:20.000000000 -0700
+++ setup-maven.sh  2010-09-07 16:14:39.000000000 -0700
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 #  Licensed to the Apache Software Foundation (ASF) under one
 #  or more contributor license agreements.  See the NOTICE file

**Comment by rvs** [comment]
Looks reasonable. Thanks for reporting it!

**Comment by rvs** [comment]
It looks like you're using older version of Oozie. Please try 2.2.0 and let me know if you still see the problem.
