### ISSUE TITLE
bundle pause should error  when set pausetime in the past

### ISSUE THREAD

**Issue by mchiang** [YahooArchive/oozie#508]
to pause coord job to an older time,
$ oozie job -change 0000024-110215232248043-oozie-oozi-C -value pausetime=2011-02-16T21:09Z
Error: E1015 : E1015: Invalid coordinator job change value 2/16/11 9:09 PM, cannot be before coordinator job's start time [Wed Feb 16 21:18:00 UTC 2011]

however, there is no such error when pause bundle to an older time. instead, oozie log:

$ oozie job -change 0000021-110215232248043-oozie-oozi-B -value pausetime=2011-02-16T21:09Z

2011-02-16 23:05:24,835  INFO BundleJobChangeXCommand:525 - USER[mchiang] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-]
BundleChangeCommand not succeeded - job 0000021-110215232248043-oozie-oozi-B finished, status is SUCCEEDED
2011-02-16 23:05:24,838  WARN XCommand:528 - USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] E1312: Bundle Job can
not be Suspended As job finished or does not exist, 0000021-110215232248043-oozie-oozi-B, Status: SUCCEEDEDError Code:
E1312

**Comment by mislam77-zz** [comment]
Done in another issue.
