### ISSUE TITLE
bundle_change did not set pausetime on a PREP bundle

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#514]
at time 2011-02-17T20:21Z, submitted a bundle, kickoff time=2011-02-17T20:30Z
then set the bundle pausetime to 2011-02-17T20:27Z.
bundle did not pause at the pausetime. the status was PREP. 
and status became RUNNING when it reached the kickoff time.

**Comment by angeloh** [comment]
Closed by e232a6a01d9863b966ba939d84b07e060b242fcc bundle_change did not set pausetime on a PREP bundle
