### ISSUE TITLE
bundle pausetime change not passed to all coord jobs

### ISSUE THREAD

**Issue by mchiang** [YahooArchive/oozie#525]
the bundle has 3 coord jobs.
change bundle pausetime.
the pausetime change was executed on 2 coord jobs, but not on the 3rd coord job.
i.e., CoordChangeXCommand did not apply to this job id when check oozie.log.

**Comment by angeloh** [comment]
Closed by dd5a8ad024e9ed17972097a118c89622b1182941 bundle pausetime change not passed to all coord jobs
