### ISSUE TITLE
release notes are not up to date since 2.2.1 tag

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#53]

**Comment by rvs** [comment]
I'll be updating tags shortly in the 2.2 branch, but I'm not quite sure what release notes you are referring to.

**Comment by tucu00** [comment]
all the commits since the code drop of 2.2 have not been recorded in the release notes.

build/test stuff mostly, but things like GH-0024 definitely merit to be in the release notes.

**Comment by rvs** [comment]
Good point. So, here's a more fundamental question. When we do a release (however minor) I take it to mean the following things:
1.  bump the version in POMs
2.  release the build of docs to gh-pages
3.  update the release notes
4.  deposit the artifacts to the public repo

Is there anything else I'm missing?

btw, I'm thinking of automating 1-4 via Maven release plugin. Will open a separate issue on that one.

**Comment by tucu00** [comment]
binary build with each release?

**Comment by rvs** [comment]
Closed by e76b0e5babf71926f12c37ab0df65dfd2626b60e release notes are not up to date since 2.2.1 tag
