### ISSUE TITLE
Oozie should not materialize a coordinator job right after its submission if the job will only run in far future.

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#55]
Currently Oozie will materialize a coordinator job right after job submission, even if the job will only run in far future. 

We need to modify CoordJobMatLookupCommand so that it also checks materialization's start time (set as job's start time for a newly submitted job) against current time. Only if it falls into a valid range (say, within one hour of future), we proceed with materialization.

**Comment by rvs** [comment]
Closed by f4607409376a984353e40b13f0e19ef4d1d22289 Oozie should not materialize a coordinator job right after its submission if the job will only run in far future
