### ISSUE TITLE
coord job should not materialize new actions when WAITING actions exceed concurrency

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#553]
for a 5min coord job in catch-up mode, it created actions for the 1st hour. so there were 1 action RUNNING, and 11
actions WAITING. $concurrency=1. however it continued to create actions for the next hour, and the total number of
actions was 24. with throttling implemented, the coord job should stop materialization for the 2nd hour.

**Comment by angeloh** [comment]
Closed by b8a1f1cfed903fcfb015a9a0c0c23df7b09bd08f coord job should not materialize new actions when WAITING actions exceed concurrency.
