### ISSUE TITLE
E0605 error is wrapped by E0603

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#564]
When rerunning a coordinator job with a non-matching date, oozie prints error E0605 that is wrapped up by E0603. Additionally, error E0302 is also printed out, which seems wrong.

$ oozie job -rerun 0000103-110222190423596-oozie-oozi-C -date 2011-01-18T19:00Z
Error: E0302 : E0302: Invalid parameter [org.apache.oozie.executor.jpa.JPAExecutorException: E0603: SQL error in
operation [org.apache.oozie.executor.jpa.JPAExecutorException: E0605: Action does not exist [2011-01-18T19:00Z]], {1}]

**Comment by angeloh** [comment]
Closed by 3c15d64b81231d06fdda40f022ef771a91fd3b87 E0605 error is wrapped by E0603
