### ISSUE TITLE
Bundle Interface feedbacks

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#571]
1\* OozieCLI uses the Json\* versions of CoordinatorAction/CoordinatorJob/BundleJob. It should use the interfaces.

2\* BundleJob misses the getCreatedTime() method.

3\* Job misses getPauseTime() and getExternalId()

4\* OozieClient inner classes _ClientCallable return Json_ lists when they return list of interfaces.

5\* LocalOozieClientCoord uses Json\* versions of CoordinatorAction/CoordinatorJob/BundleJob. It should use the interfaces.

**Comment by mislam77-zz** [comment]
Done in another issue.
