### ISSUE TITLE
Commons CLI2 maven artifact is commons-cli2

### ISSUE THREAD

**Issue by cwilkes** [YahooArchive/oozie#6]
mvn install from http://svn.apache.org/repos/asf/commons/sandbox/cli2/trunk creates an artifact with this info:

 <groupId>org.apache.commons</groupId>
  <artifactId>commons-cli2</artifactId>
  <version>2.0-SNAPSHOT</version>

**Comment by tucu00** [comment]
There is no need for CLI2, Issue 9 removes that dependency.

**Comment by mislam77-zz** [comment]
Not valid for oozie 2.2.x. Closing the issue.
