### ISSUE TITLE
actions should not be materialized after nominal time for current mode jobs

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#60]
I ran a coordinator job under current mode, then check its status:

[chaow@pressglass examples]$ oozie job -info 0000007-100727102157647-oozie-chao-C

ID                            Created                Nominal Time
...
0000007-......@2  2010-07-27 19:41     2010-07-27 19:40
...

We see that creation time is after nominal time, which is not correct.
Note here the cluster is not stressed at all - so actions should be created a bit earlier than the nominal time.

**Comment by bansalmayank** [comment]
Closed by 01bcec28b4cd0617206433c3cc9c004fd7f247b1 actions should not be materialized after nominal time for current mode jobs
