### ISSUE TITLE
display configuration content for bundle jobs 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#613]
currently the -configcontent supports coord jobs and wf jobs, but not bundle jobs.

$ oozie job -configcontent 0000006-110215232248043-oozie-oozi-B
ERROR:  job id [0000006-110215232248043-oozie-oozi-B] doesn't end with either C or W

**Comment by bansalmayank** [comment]
Closed by 242c28aafd46e1e3d68f08f976e77a2accb26700 display configuration content for bundle jobs
