### ISSUE TITLE
Add a new schema support for bundle xml into oozie

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#63]
It includes:
- a new bundle xsd file 
- SchemaService should instantiate that xsd. 
- A related test case should be provided.

**Comment by tucu00** [comment]
Before continuing with bundle related issues it would be worth agreeing on GH-0049

**Comment by mislam77-zz** [comment]
We already started working on the other internal techdebt list.
It is being agreed that we will give intermediate drop to our customer with a subset of features. It will help our user to incrementally test the new features.

**Comment by mislam77-zz** [comment]
closed in another issue
