### ISSUE TITLE
coord job status is not PAUSED at pausetime 

### ISSUE THREAD

**Issue by mchiang** [YahooArchive/oozie#630]
submit a 10min coord job (normal mode). start=2011-03-17T20:03Z, end=2011-03-17T21:03Z, so it creates 6 actions initially.
set pausetime=2011-03-17T20:05Z. then action 2-6 are removed because of the pausetime. this is correct.
however, the coord job status is not set to PAUSED at pausetime. it becomes SUCCEEDED.

**Comment by bansalmayank** [comment]
Closed by 1e73345e49032e8d2dcc50f5c0ba1584abc84c5a Fixing Paused status for Coordinator
