### ISSUE TITLE
remove extra fields in oozie jobs -jobtype bundle -verbose 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#632]
in the -verbose detail report, there are some fields that are not relevant to bundle jobs: External ID, Unit, Timeout. 

$ oozie jobs -jobtype bundle -len 1 -offset 1 -verbose
Job ID  Bundle Name     Bundle Path     User    Group   Status  Kickoff Pause   Created Console URL     External IDUnit
##     Timeout

0000130-110304215922951-oozie-oozi-B    test-44-3  
hdfs://gsbl90359.blue.ygrid.yahoo.com:8020/user/mchiang/yoozie_test/coord/test_b44-1/bundle3.xml    mchiang users

**Comment by bansalmayank** [comment]
Closed by a4c2166da5810f9bed51d49d085af7df261c2380 remove extra fields in oozie jobs -jobtype bundle -verbose.
