### ISSUE TITLE
[BUNDLE] coord job should be started immediately if no kick-off time specified in bundle.xml. 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#636]
coord job should be started immediately if no kick-off time specified in bundle.xml.

<bundle-app name='BUNDLE-TEST' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xmlns='uri:oozie:bundle:0.1'> 
   <coordinator name='coordJobFromBundle' >
                 <app-path>${appPath}</app-path>
       <configuration>
         <property>
              <name>START_TIME</name>
              <value>${START_TIME}</value>
          </property>
         <property>
              <name>END_TIME</name>
              <value>${END_TIME}</value>
          </property>
      </configuration>
   </coordinator>
</bundle-app>

**Comment by bansalmayank** [comment]
Closed by 73b11cf954ac8904571e071fcb2bd2540442248c coord job should be started immediately if no kick-off time specified in bundle.xml.
