### ISSUE TITLE
Need some developer docs for getting started to contribute to oozie

### ISSUE THREAD

**Issue by shivajayaraman** [YahooArchive/oozie#638]
Couldnt find docs that describe how to 
- clone the project
- build using maven
- set up eclipse projects (or other IDEs)
- and how to run the JUnit tests 

It would be very helpful if we had those.

**Comment by tucu00** [comment]
This information is avail in Oozie website docs:

  https://github.com/yahoo/oozie/wiki/How-To-Contribute

  http://yahoo.github.com/oozie/releases/2.3.0/ENG_Building.html
