### ISSUE TITLE
Create a config to turn on openjpa log

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#64]
Add one config to turn on openjpa log.

**Comment by tucu00** [comment]
why do we need to do this?

You can just add the log level in the oozie-log4j.properties for the openjpa package and you are done.

**Comment by angeloh** [comment]
To turn on openjpa log, we have to add one property to persistence.xml.

**Comment by angeloh** [comment]
please review it. http://github.com/angelokh/oozie/commit/7f06dceec2367d54546726e427075236419fe5ce

**Comment by angeloh** [comment]
Actually, I can make openjpa.log output to log4j. So user can turn on the openjpa.log in oozie-site. Then, give the openjpa's log4j properties to oozie-log4j. What do you think?

**Comment by tucu00** [comment]
If I understand correctly you are proposing:
- OPEN JPA will be configured to always log to LOG4J
- oozie-log4j.properties configuration will have entries for openjpa to the logger
- to enable OPENJPA the oozie admin will have to change the log level in oozie-log4j.properties

If this is what you are proposing, +1

**Comment by angeloh** [comment]
Yes, correct. As for oozie-log4j.properties configuration will have entries for openjpa to the logger, should those entries be commented out in default?

**Comment by tucu00** [comment]
the should be set to INFO, unless JPA spits its guts in INFO level

**Comment by angeloh** [comment]
Per tucu's suggestions, I resubmit this commit. Please review it.
http://github.com/angelokh/oozie/commit/cb2d8f8924e8b5d3552a53a375d8a33e0f011c5d

**Comment by mislam77-zz** [comment]
+1

**Comment by angeloh** [comment]
Closed by 15f8dbd0e6948d5b0963dcfd8bee695e45886b5e Create a config to turn on openjpa log
