### ISSUE TITLE
rerun TIMEDOUT action and it uses the timeout value and timedout again 

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#647]
when rerun a TIMEDOUT action, since the clock time already passes the nominal time, it's like re-running this action in
"catch up" mode.
in "catch up" mode, the timeout value is set to "-1".

currently the rerun still uses the original timeout value as defined in coordinator.xml.

**Comment by angeloh** [comment]
Closed by 33552eb72d10e0a9562710820f6233b5af6b9885 rerun TIMEDOUT action and it uses the timeout value and timedout again
