### ISSUE TITLE
Bad link to 2.2.0 download from quick start page

### ISSUE THREAD

**Issue by cwilkes** [YahooArchive/oozie#7]
this page: http://yahoo.github.com/oozie/releases/2.2.0/DG_QuickStart.html 
links to both http://yahoo.github.com/oozie/downloads (from the view of the HTML) and http://yahoo.github.com/oozie/releases/2.2.0/Http://yahoo.github.com/oozie/downloads.html as the actual link.  Neither of which are valid.

**Comment by rvs** [comment]
Thanks for the report. I'll take care of it shortly.

**Comment by rvs** [comment]
Fixed. 

Next time feel free to fork and and send me a pull request ;-)
