### ISSUE TITLE
Pause a coordinator bundle

### ISSUE THREAD

**Issue by marcychen** [YahooArchive/oozie#71]
Pause a coordinator bundle at a certain timestamp and run the pipeline up to that timestamp.  A pipeline is defined by a single coordinator bundle. By pausing the pipeline, we will run all the workflow instances defined in the coordinator jobs within the bundle up to the timestamp at which the pipeline will be paused. No new workflow instances will be submitted.

**Comment by mislam77-zz** [comment]
Done in another issue.
