### ISSUE TITLE
Resume a coordinator bundle

### ISSUE THREAD

**Issue by marcychen** [YahooArchive/oozie#72]
Resume a coordinator bundle that has been suspended. The system will go through a "catch-up" period and process all jobs up to the current timestamp before normal processing begins. Catch-up is defined at the coordinator job level. The rate of catch-up job submission should be configurable in the coordinator job, which can be overridden at the bundle level.

**Comment by mislam77-zz** [comment]
Done in another issue.

**Comment by mislam77-zz** [comment]
Done in another issue.
