### ISSUE TITLE
 Provide access to date list.

### ISSUE THREAD

**Issue by marcychen** [YahooArchive/oozie#75]
We will provide functions for customers to access the following information: a) Nominal time when the coordinator jobs are supposed to start b) Name for each coordinator job/action inside the bundle and c) List of dates (UTC format) given the start date, end date and  frequency.

**Comment by mislam77-zz** [comment]
(a) is already there.
(b) is not clear about the requirement.
We are planning to address (c) in this issue.
We plan to add an coordinator level EL functions like coord:date_list(start_time_in_utc, end_time_in_utc, frequency, timezone)

There could be other form:
 coord:date_list(start_time_in_utc, end_time_in_utc) which will use the frequency and TZ of coordinator application.

Please give your comments.

**Comment by angeloh** [comment]
Closed by 651cf6157ab4c50bc6c176e11323063d552d5f9d Provide access to date list.
