### ISSUE TITLE
Clean up temporary files in the user HDFS directory upon completion and provide "-skipTrash" option on delete.

### ISSUE THREAD

**Issue by marcychen** [YahooArchive/oozie#86]
Oozie generates about 35000 directories and 15000 files which fills the name space quota 50000.  We would expect oozie to remove the temporary directories/files once the workflow is done.

**Comment by mislam77-zz** [comment]
Although action dir is deleted, the directory with WFID is not deleted.
We need to delete the dir with WFID when the WF job ends.
In other words, we have to find all the places where the job's status is set to terminal states (SUCCEEDED, KILLED, FAILED). Then remove the dir with WFDI.

Any comments?

**Comment by bansalmayank** [comment]
Closed by ce293b0776880e4ab3dae0b915a1928ed0253487 Clean up temporary files in the user HDFS directory upon completion
