### ISSUE TITLE
XCommand Code refactoring 

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#98]
Oozie Xcommand Refactoring.

**Comment by angeloh** [comment]
JPA command refactor : http://github.com/yahoo/oozie/issues/issue/99

**Comment by bansalmayank** [comment]
Closed by bcb508867530d6f491a1dfdd3e5f7e6888e84002 Adding the Xcommand for command refactoring.

**Comment by bansalmayank** [comment]
Closed by bcb508867530d6f491a1dfdd3e5f7e6888e84002 Adding the Xcommand for command refactoring.

**Comment by brookwc** [comment]
Closed by 9ae23699d3e8ae3719bc3bad642d274911f7df3d Adding the Xcommand for command refactoring.
