### ISSUE TITLE
JPA command refactor

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#99]
This issue only address JPA command refactor. Please refer to parent issue for other details:http://github.com/yahoo/oozie/issues/issue/98.

**Comment by angeloh** [comment]
Closed by 59b215b81beeecefc69ce245697c3c0cb464c090 Add JPACommand

**Comment by angeloh** [comment]
Closed by 59b215b81beeecefc69ce245697c3c0cb464c090 Add JPACommand

**Comment by mislam77-zz** [comment]
Done in another issue.
